# Generated by Django 4.2.4 on 2023-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=155, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='web',
            field=models.URLField(blank=True, verbose_name='Web Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zip Code'),
        ),
    ]
